import type { CardDef, Faction } from './types';

/**
 * The full BOLOSS card catalog (71 cards across 5 factions), transcribed from
 * the artwork in carte.zip.
 *
 * Effects are data-driven where the engine has a generic handler for them.
 * A handful of very bespoke cards (Dios Mios, Reboot, Contract Révolutionnaire,
 * and the vaguer "péchés capitaux") are resolved by dedicated code paths in the
 * engine keyed on the card id — see engine.ts `SPECIAL_ACTS`.
 */

/** ids of the seven deadly sins — used by the SEVEN_SINS summoning condition. */
export const SIN_IDS = [
  'avocat_gourmandise',
  'avocat_luxure',
  'avocat_paresse',
  'avocat_colere',
  'avocat_avarice',
  'avocat_envie',
  'avocat_orgueil',
] as const;

const CARDS: CardDef[] = [
  /* ============================================================= *
   *  AVOCAT DU DIABLE — the seven deadly sins
   * ============================================================= */
  {
    id: 'avocat_hero',
    name: 'Avocat du Diable',
    faction: 'avocat',
    type: 'HERO',
    rank: 'A',
    image: 'avocat_hero.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Argument de Merde',
    attackDesc: "Une logique à en blesser le cerveau de l'adversaire.",
  },
  {
    id: 'avocat_idee_merde',
    name: 'Idée de Merde',
    faction: 'avocat',
    type: 'INVOCATION',
    rank: 'C',
    image: 'avocat_idee_merde.jpg',
    baseHp: 40,
    baseAttack: 20,
    attackName: 'Idée Diablotine',
    attackDesc: "Influence l'adversaire à se blesser lui-même.",
  },
  {
    id: 'avocat_idee_bienveillante',
    name: 'Idée Bienveillante',
    faction: 'avocat',
    type: 'INVOCATION',
    rank: 'C',
    image: 'avocat_idee_bienveillante.jpg',
    baseHp: 40,
    baseAttack: 20,
    attackName: 'Idée Angéline',
    attackDesc: "Séduit l'adversaire pour qu'il se blesse lui-même.",
  },
  {
    id: 'avocat_contract_fourberie',
    name: 'Contract de Fourberie',
    faction: 'avocat',
    type: 'OBJET',
    rank: 'B',
    image: 'avocat_contract_fourberie.jpg',
    effectText: "Fourberie de Satan — équipe une invocation adverse : elle subit -10 HP pendant 3 tours.",
    effects: [{ trigger: 'ON_PLAY', action: 'POISON', target: 'ENEMY_INVOCATION', value: 10, duration: 3 }],
  },
  {
    id: 'avocat_poulet_maroille',
    name: 'Poulet Sauce Maroille',
    faction: 'avocat',
    type: 'OBJET',
    rank: 'A',
    image: 'avocat_poulet_maroille.jpg',
    effectText: 'Consomme le — Donne +60 HP.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_CHARACTER', value: 60, duration: 'PERMANENT' }],
  },
  {
    id: 'avocat_gourmandise',
    name: 'Gourmandise',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_gourmandise.jpg',
    effectText: 'Péché capital. Ton HÉRO gagne +20 HP.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_HERO', value: 20, duration: 'PERMANENT' }],
  },
  {
    id: 'avocat_luxure',
    name: 'Luxure',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_luxure.jpg',
    effectText: 'Péché capital. Séduction manipulatrice.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'FLAVOR' }],
  },
  {
    id: 'avocat_paresse',
    name: 'Paresse',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_paresse.jpg',
    effectText: 'Péché capital. Empêche les invocations adverses d\'attaquer pendant 1 tour.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'CANNOT_ATTACK', target: 'ENEMY_INVOCATION', massTarget: true, duration: 1 }],
  },
  {
    id: 'avocat_colere',
    name: 'Colère',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_colere.jpg',
    effectText: 'Péché capital. +20 attaque à toutes tes invocations ce tour-ci.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_INVOCATION', massTarget: true, value: 20, duration: 1 }],
  },
  {
    id: 'avocat_avarice',
    name: 'Avarice',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_avarice.jpg',
    effectText: 'Péché capital. La cupidité incarnée.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'FLAVOR' }],
  },
  {
    id: 'avocat_envie',
    name: 'Envie',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_envie.jpg',
    effectText: 'Péché capital. La jalousie te ronge.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'FLAVOR' }],
  },
  {
    id: 'avocat_orgueil',
    name: 'Orgueil',
    faction: 'avocat',
    type: 'ACT',
    rank: 'B',
    image: 'avocat_orgueil.jpg',
    effectText: 'Péché capital. La fierté avant la chute.',
    tags: ['sin'],
    effects: [{ trigger: 'ON_PLAY', action: 'FLAVOR' }],
  },
  {
    id: 'avocat_veritable_avocat',
    name: 'Véritable Avocat du Diable',
    faction: 'avocat',
    type: 'INVOCATION',
    rank: 'S',
    image: 'avocat_veritable_avocat.jpg',
    baseHp: 100,
    baseAttack: 110,
    attackName: 'Idée Tranchante',
    attackDesc: 'Manipulation du Diable — une logique implacable.',
    summoningConditions: [{ type: 'SEVEN_SINS', count: 7 }],
  },
  {
    id: 'avocat_lancer_tortue',
    name: 'Lancer de Tortue',
    faction: 'avocat',
    type: 'ACT',
    rank: 'C',
    image: 'avocat_lancer_tortue.jpg',
    effectText: '-10 HP sur une invocation.',
    effects: [{ trigger: 'ON_PLAY', action: 'DAMAGE', target: 'ANY_INVOCATION', value: 10 }],
  },
  {
    id: 'avocat_ange_raison',
    name: 'Véritable Ange de la Raison',
    faction: 'avocat',
    type: 'INVOCATION',
    rank: 'S',
    image: 'avocat_ange_raison.jpg',
    baseHp: 100,
    baseAttack: 110,
    attackName: 'Force de la Raison',
    attackDesc: 'Omnipotence Divine — la raison tranche toute chose.',
    summoningConditions: [{ type: 'SEVEN_SINS', count: 7 }],
  },

  /* ============================================================= *
   *  TYRANNIE FLORALE — plantes, rois & chevaliers
   * ============================================================= */
  {
    id: 'floral_hero',
    name: 'Tyrannie Florale',
    faction: 'floral',
    type: 'HERO',
    rank: 'A',
    image: 'floral_hero.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Soumission Absurde',
    attackDesc: "Pousse l'adversaire à se frapper lui-même.",
  },
  {
    id: 'floral_fleur_sauvage',
    name: 'Fleur So Sauvage',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'C',
    image: 'floral_fleur_sauvage.jpg',
    baseHp: 40,
    baseAttack: 20,
    attackName: 'Lance Bourrine',
    attackDesc: 'Tape dans tous les sens avec sa lance.',
  },
  {
    id: 'floral_fleur_tankeuse',
    name: 'Fleur Tankeuse',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'C',
    image: 'floral_fleur_tankeuse.jpg',
    baseHp: 30,
    baseAttack: 10,
    attackName: 'Charge Stupide',
    attackDesc: "Provocation — les ennemis sont obligés de l'attaquer.",
    effects: [{ trigger: 'PASSIVE', action: 'TAUNT', text: 'Provocation' }],
  },
  {
    id: 'floral_reine_rosy',
    name: "Reine Rosy l'Amoureuse",
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'B',
    image: 'floral_reine_rosy.jpg',
    baseHp: 50,
    baseAttack: 10,
    attackName: 'Monarchie Florale',
    attackDesc: '+10 HP et +10 attaque à toutes les invocations florales.',
    effects: [{ trigger: 'PASSIVE', action: 'AURA_BUFF', faction: 'floral', value: 10, auraHp: 10, text: 'Monarchie Florale' }],
  },
  {
    id: 'floral_roi_roso',
    name: "Roi Roso l'Amoureux",
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'B',
    image: 'floral_roi_roso.jpg',
    baseHp: 50,
    baseAttack: 10,
    attackName: 'Monarchie Florale',
    attackDesc: '+10 HP et +10 attaque à toutes les invocations florales.',
    effects: [{ trigger: 'PASSIVE', action: 'AURA_BUFF', faction: 'floral', value: 10, auraHp: 10, text: 'Monarchie Florale' }],
  },
  {
    id: 'floral_amour_royal',
    name: 'Amour Royal Floral',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'A',
    image: 'floral_amour_royal.jpg',
    baseHp: 80,
    baseAttack: 40,
    attackName: 'By the Power of Love',
    attackDesc: "C'est ça la puissance de l'amour.",
    summoningConditions: [
      { type: 'SACRIFICE_INVOCATION', match: { cardId: 'floral_roi_roso' }, count: 1 },
      { type: 'SACRIFICE_INVOCATION', match: { cardId: 'floral_reine_rosy' }, count: 1 },
    ],
  },
  {
    id: 'floral_guerrier_solaire',
    name: 'Guerrier Solaire',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'B',
    image: 'floral_guerrier_solaire.jpg',
    baseHp: 50,
    baseAttack: 20,
    attackName: 'Enchaînement Solaire',
    attackDesc: 'Tape si fort que son épée chauffe comme le soleil.',
  },
  {
    id: 'floral_champ_bataille',
    name: 'Champ de Bataille Floral',
    faction: 'floral',
    type: 'OBJET',
    rank: 'B',
    image: 'floral_champ_bataille.jpg',
    effectText: '+20 attaque — uniquement sur une invocation florale.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_INVOCATION', faction: 'floral', value: 20, duration: 'PERMANENT' }],
  },
  {
    id: 'floral_chevalier_mousses',
    name: 'Chevalier de Mousses',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'A',
    image: 'floral_chevalier_mousses.jpg',
    baseHp: 60,
    baseAttack: 40,
    attackName: 'Écharde Tranchante',
    attackDesc: 'Sacrifie toutes les fleurs de rang C.',
    summoningConditions: [{ type: 'SACRIFICE_INVOCATION', match: { faction: 'floral', rank: 'C' }, count: 4 }],
  },
  {
    id: 'floral_chevalier_florissant',
    name: 'Chevalier Florissant',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'A',
    image: 'floral_chevalier_florissant.jpg',
    baseHp: 50,
    baseAttack: 30,
    attackName: 'Écharde Tranchante',
    attackDesc: 'Sacrifie le Roi Roso.',
    summoningConditions: [{ type: 'SACRIFICE_INVOCATION', match: { cardId: 'floral_roi_roso' }, count: 1 }],
  },
  {
    id: 'floral_fleur_flingue_c',
    name: 'Fleure avec un Flingue',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'C',
    image: 'floral_fleur_flingue_c.jpg',
    baseHp: 40,
    baseAttack: 10,
    attackName: 'Pan Pan',
    attackDesc: "C'est une fleur, elle ne sait pas tirer.",
  },
  {
    id: 'floral_fleur_flingue_a',
    name: 'Fleure Royale avec un Flingue',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'A',
    image: 'floral_fleur_flingue_a.jpg',
    baseHp: 20,
    baseAttack: 10,
    attackName: 'Coup de Sceptre',
    attackDesc: 'Karma Floral — à sa mort, invoque le Dévoreur de Papillons depuis ton deck.',
    effects: [{ trigger: 'ON_DEATH', action: 'SUMMON_FROM_DECK', summonCardId: 'floral_devoreur_papillons', text: 'Karma Floral' }],
  },
  {
    id: 'floral_devoreur_papillons',
    name: 'Dévoreur de Papillons',
    faction: 'floral',
    type: 'INVOCATION',
    rank: 'A',
    image: 'floral_devoreur_papillons.jpg',
    baseHp: 20,
    baseAttack: 80,
    attackName: 'Coup Brutal',
    attackDesc: 'Libération — peut attaquer dès son invocation.',
    effects: [{ trigger: 'PASSIVE', action: 'CHARGE', text: 'Libération' }],
  },
  {
    id: 'floral_coup_pression',
    name: 'Coup de Pression',
    faction: 'floral',
    type: 'ACT',
    rank: 'B',
    image: 'floral_coup_pression.jpg',
    effectText: '+30 attaque à une invocation ce tour-ci (elle frappe plus fort).',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_INVOCATION', value: 30, duration: 1 }],
  },
  {
    id: 'floral_revolver_violet',
    name: 'Revolver Violet',
    faction: 'floral',
    type: 'OBJET',
    rank: 'C',
    image: 'floral_revolver_violet.jpg',
    effectText: 'Pression Mortelle — +10 attaque pendant 6 tours.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 10, duration: 6 }],
  },

  /* ============================================================= *
   *  LA FERME DE JULES — fermiers & gros équipements
   * ============================================================= */
  {
    id: 'jules_hero',
    name: 'Jeune Disciple Fermier',
    faction: 'jules',
    type: 'HERO',
    rank: 'A',
    image: 'jules_hero.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Coup de Pelle',
    attackDesc: 'Sort sa grosse pelle pour te frapper avec.',
  },
  {
    id: 'jules_vieux_fermier',
    name: 'Vieux Fermier Affirmé',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'A',
    image: 'jules_vieux_fermier.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Coup de Râteau',
    attackDesc: 'Sort son gros râteau pour te frapper avec.',
  },
  {
    id: 'jules_woinic',
    name: 'Woinic',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'B',
    image: 'jules_woinic.jpg',
    baseHp: 60,
    baseAttack: 20,
    attackName: 'Charge du Sanglier',
    attackDesc: 'Fonce dans son adversaire à toute vitesse.',
  },
  {
    id: 'jules_tiramisu',
    name: 'Tiramisu Empoisonné',
    faction: 'jules',
    type: 'OBJET',
    rank: 'B',
    image: 'jules_tiramisu.jpg',
    effectText: 'Empoisonnement — équipe une invocation adverse : -10 HP pendant 3 tours.',
    effects: [{ trigger: 'ON_PLAY', action: 'POISON', target: 'ENEMY_INVOCATION', value: 10, duration: 3 }],
  },
  {
    id: 'jules_vache_enragee',
    name: 'Vache Enragée',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'B',
    image: 'jules_vache_enragee.jpg',
    baseHp: 60,
    baseAttack: 20,
    attackName: 'Charge de la Vache',
    attackDesc: 'Fonce dans son adversaire à toute vitesse.',
  },
  {
    id: 'jules_musique',
    name: 'Musique Inoubliable',
    faction: 'jules',
    type: 'OBJET',
    rank: 'C',
    image: 'jules_musique.jpg',
    effectText: '+20 HP à une invocation.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_INVOCATION', value: 20, duration: 'PERMANENT' }],
  },
  {
    id: 'jules_coureur_fou',
    name: 'Coureur Fou',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'B',
    image: 'jules_coureur_fou.jpg',
    baseHp: 50,
    baseAttack: 20,
    attackName: 'Sprint Éclair',
    attackDesc: 'Court si vite qu\'il crée une tornade qui terrasse son adversaire.',
  },
  {
    id: 'jules_frappe_explosive',
    name: 'Frappe Explosive',
    faction: 'jules',
    type: 'ACT',
    rank: 'B',
    image: 'jules_frappe_explosive.jpg',
    effectText: '-10 HP pour toutes les invocations (même les vôtres).',
    effects: [{ trigger: 'ON_PLAY', action: 'DAMAGE_ALL_INVOCATIONS', value: 10 }],
  },
  {
    id: 'jules_stade',
    name: 'Stade du Village Fermier',
    faction: 'jules',
    type: 'OBJET',
    rank: 'B',
    image: 'jules_stade.jpg',
    effectText: 'Sport & Passion — +20 attaque à une invocation.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_INVOCATION', value: 20, duration: 'PERMANENT' }],
  },
  {
    id: 'jules_faue_mort',
    name: 'Faux de la Mort du Fermier',
    faction: 'jules',
    type: 'OBJET',
    rank: 'A',
    image: 'jules_faue_mort.jpg',
    effectText: 'Équipement de Fermier — +60 attaque pendant 1 tour.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 60, duration: 1 }],
  },
  {
    id: 'jules_idee_ennui',
    name: "Idée pour Contrer l'Ennui",
    faction: 'jules',
    type: 'OBJET',
    rank: 'F',
    image: 'jules_idee_ennui.jpg',
    effectText: 'Jeu de Cartes Maison — carte collector, aucun effet. Sois fier de toi.',
    effects: [{ trigger: 'ON_PLAY', action: 'FLAVOR' }],
  },
  {
    id: 'jules_fusil_pompe',
    name: 'Fusil à Pompe du Fermier',
    faction: 'jules',
    type: 'OBJET',
    rank: 'B',
    image: 'jules_fusil_pompe.jpg',
    effectText: 'Pan ! — +20 attaque.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 20, duration: 'PERMANENT' }],
  },
  {
    id: 'jules_hero_rpg',
    name: 'Héro de RPG Cliché',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'A',
    image: 'jules_hero_rpg.jpg',
    baseHp: 70,
    baseAttack: 30,
    attackName: 'Coup de Grosse Épée',
    attackDesc: 'HAYAAAAAAAA !!!!!',
  },
  {
    id: 'jules_chevalier_imaginaire',
    name: 'Chevalier du Pays Imaginaire',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'A',
    image: 'jules_chevalier_imaginaire.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Coup Sortie de Nulle Part',
    attackDesc: 'Improvise un coup qui surprend son adversaire.',
  },
  {
    id: 'jules_empereur_galactique',
    name: 'Empereur Galactique',
    faction: 'jules',
    type: 'INVOCATION',
    rank: 'A',
    image: 'jules_empereur_galactique.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Charge de Fierté',
    attackDesc: 'Charge pour prouver son courage et sa fierté.',
  },

  /* ============================================================= *
   *  MONSTER HUNTER — bêtes & sacrifices
   * ============================================================= */
  {
    id: 'monster_hero',
    name: 'Reine des Pyrobarbares',
    faction: 'monster',
    type: 'HERO',
    rank: 'A',
    image: 'monster_hero.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Flamme Fatale',
    attackDesc: 'Brûle son adversaire pour son plaisir.',
  },
  {
    id: 'monster_chasseuse',
    name: 'Chasseuse de Monstres',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'A',
    image: 'monster_chasseuse.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Tranchant Cuirasse',
    attackDesc: 'Tape avec son épée capable de trancher les peaux les plus dures.',
  },
  {
    id: 'monster_poulet_feuilete',
    name: 'Poulet Feuilleté',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'C',
    image: 'monster_poulet_feuilete.jpg',
    baseHp: 30,
    baseAttack: 0,
    attackName: 'Rugissement de la Volaille',
    attackDesc: 'Cri insupportable — les invocations adverses sont obligées de l\'attaquer.',
    effects: [{ trigger: 'PASSIVE', action: 'TAUNT', text: 'Provocation' }],
  },
  {
    id: 'monster_esprit_bouffi',
    name: 'Esprit Bouffi',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'C',
    image: 'monster_esprit_bouffi.jpg',
    baseHp: 50,
    baseAttack: 10,
    attackName: 'Morsure Sucrée',
    attackDesc: "Mord son adversaire en pensant que c'est un bonbon ou de la viande.",
  },
  {
    id: 'monster_mangeuse',
    name: "Mangeuse d'Homme",
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'B',
    image: 'monster_mangeuse.jpg',
    baseHp: 50,
    baseAttack: 30,
    attackName: 'Morsure Sauvage',
    attackDesc: 'Broie vos tripes avec ses cheveux lui servant de mâchoires.',
  },
  {
    id: 'monster_loup_combattant',
    name: 'Loup Combattant',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'B',
    image: 'monster_loup_combattant.jpg',
    baseHp: 50,
    baseAttack: 30,
    attackName: 'Griffes Destructrices',
    attackDesc: "Entoure ses griffes d'une aura bleue qui renforce sa force.",
  },
  {
    id: 'monster_esprit_nocturne',
    name: 'Esprit Animal Nocturne',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'B',
    image: 'monster_esprit_nocturne.jpg',
    baseHp: 50,
    baseAttack: 20,
    attackName: 'Enchaînement Lunaire',
    attackDesc: "Tape si vite qu'il se met à briller comme la pleine lune.",
  },
  {
    id: 'monster_loup_tenebres',
    name: 'Loup des Ténèbres',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'A',
    image: 'monster_loup_tenebres.jpg',
    baseHp: 60,
    baseAttack: 40,
    attackName: 'Âme Vengeresse',
    attackDesc: 'Invoque des âmes pour te frapper. Sacrifie 2 Esprits Bouffis.',
    summoningConditions: [{ type: 'SACRIFICE_INVOCATION', match: { cardId: 'monster_esprit_bouffi' }, count: 2 }],
  },
  {
    id: 'monster_abysses',
    name: 'Monstres des Abysses',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'A',
    image: 'monster_abysses.jpg',
    baseHp: 60,
    baseAttack: 40,
    attackName: 'Vague Surpuissante',
    attackDesc: 'Envoie un tsunami. Sacrifie tous les monstres de rang C (4).',
    summoningConditions: [{ type: 'SACRIFICE_INVOCATION', match: { faction: 'monster', rank: 'C' }, count: 4 }],
  },
  {
    id: 'monster_chauve_souris',
    name: 'Chauve-Souris Sonique',
    faction: 'monster',
    type: 'INVOCATION',
    rank: 'C',
    image: 'monster_chauve_souris.jpg',
    baseHp: 50,
    baseAttack: 10,
    attackName: 'Vitesse du Son',
    attackDesc: "Un ultrason assez puissant pour t'atteindre physiquement.",
  },

  /* ============================================================= *
   *  SOLDAT ROUGE — révolution & cuivre
   * ============================================================= */
  {
    id: 'soldat_hero',
    name: 'Agent des Forces Rouges',
    faction: 'soldat',
    type: 'HERO',
    rank: 'A',
    image: 'soldat_hero.jpg',
    baseHp: 80,
    baseAttack: 30,
    attackName: 'Métal Rebelle',
    attackDesc: 'Te frappe avec un bout de métal trouvé sur le chemin.',
  },
  {
    id: 'soldat_bienveillant',
    name: 'Soldat Bienveillant',
    faction: 'soldat',
    type: 'INVOCATION',
    rank: 'C',
    image: 'soldat_bienveillant.jpg',
    baseHp: 40,
    baseAttack: 20,
    attackName: 'Correction Bienveillante',
    attackDesc: "Tire dans le pied de son adversaire pour lui apprendre la paix.",
  },
  {
    id: 'soldat_rebelle',
    name: 'Rebelle Révolutionnaire',
    faction: 'soldat',
    type: 'INVOCATION',
    rank: 'C',
    image: 'soldat_rebelle.jpg',
    baseHp: 30,
    baseAttack: 20,
    attackName: 'High Kick',
    attackDesc: 'URA URA URA URA ! Appel de la Révolution — à sa mort, un autre Rebelle sort du deck pour le remplacer.',
    effects: [{ trigger: 'ON_DEATH', action: 'SUMMON_FROM_DECK', summonCardId: 'soldat_rebelle', text: 'Appel de la Révolution' }],
  },
  {
    id: 'soldat_batte',
    name: 'Batte du Révolutionnaire',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'B',
    image: 'soldat_batte.jpg',
    effectText: 'Frappe Fatale — +30 attaque.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 30, duration: 'PERMANENT' }],
  },
  {
    id: 'soldat_dios_mios',
    name: 'Dios Mios',
    faction: 'soldat',
    type: 'ACT',
    rank: 'A',
    image: 'soldat_dios_mios.jpg',
    effectText: 'Renvoie au cimetière une invocation adverse nécessitant un sacrifice.',
    // Bespoke removal — resolved in engine (SPECIAL_ACTS).
  },
  {
    id: 'soldat_bandana',
    name: 'Bandana Révolutionnaire',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'A',
    image: 'soldat_bandana.jpg',
    effectText: 'Espoir de Révolution — +40 HP.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_CHARACTER', value: 40, duration: 'PERMANENT' }],
  },
  {
    id: 'soldat_lombric',
    name: 'Lombric Guerrier',
    faction: 'soldat',
    type: 'INVOCATION',
    rank: 'B',
    image: 'soldat_lombric.jpg',
    baseHp: 50,
    baseAttack: 20,
    attackName: 'Appuie sur une Gâchette',
    attackDesc: "Does he know ? He dosn't know.",
  },
  {
    id: 'soldat_reboot',
    name: 'Reboot',
    faction: 'soldat',
    type: 'ACT',
    rank: 'B',
    image: 'soldat_reboot.jpg',
    effectText: 'Reprend un objet équipé sur une de tes invocations dans ta main.',
    // Bespoke un-equip — resolved in engine (SPECIAL_ACTS).
  },
  {
    id: 'soldat_chat',
    name: 'Chat',
    faction: 'soldat',
    type: 'INVOCATION',
    rank: 'A',
    image: 'soldat_chat.jpg',
    baseHp: 60,
    baseAttack: 40,
    attackName: 'Roulade Tactique',
    attackDesc: 'Te roule dessus et ne peut pas s\'arrêter. Sacrifie le Soldat Bienveillant et 3 objets.',
    summoningConditions: [
      { type: 'SACRIFICE_INVOCATION', match: { cardId: 'soldat_bienveillant' }, count: 1 },
      { type: 'SACRIFICE_OBJECT', count: 3 },
    ],
  },
  {
    id: 'soldat_grenade',
    name: 'Grenade de la Révolution',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'A',
    image: 'soldat_grenade.jpg',
    effectText: 'Explosion Définitrice — +80 attaque pendant 1 tour.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 80, duration: 1 }],
  },
  {
    id: 'soldat_burger',
    name: 'Le Roi du Burger',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'C',
    image: 'soldat_burger.jpg',
    effectText: 'Consomme le — +10 HP.',
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_CHARACTER', value: 10, duration: 'PERMANENT' }],
  },
  {
    id: 'soldat_armure_cuivre',
    name: 'Armure de Cuivres',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'A',
    image: 'soldat_armure_cuivre.jpg',
    effectText: 'Armure du Bling — +50 HP pendant 3 tours.',
    tags: ['cuivre'],
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_HP', target: 'ALLIED_CHARACTER', value: 50, duration: 3 }],
  },
  {
    id: 'soldat_arme_cuivre',
    name: 'Arme de Cuivres',
    faction: 'soldat',
    type: 'OBJET',
    rank: 'A',
    image: 'soldat_arme_cuivre.jpg',
    effectText: 'Arme du Bling — +50 attaque pendant 3 tours.',
    tags: ['cuivre'],
    effects: [{ trigger: 'ON_PLAY', action: 'BUFF_ATTACK', target: 'ALLIED_CHARACTER', value: 50, duration: 3 }],
  },
  {
    id: 'soldat_contract_revo',
    name: 'Contract Révolutionnaire',
    faction: 'soldat',
    type: 'ACT',
    rank: 'B',
    image: 'soldat_contract_revo.jpg',
    effectText: "Prends le contrôle d'une invocation adverse (si tu as de la place).",
    // Bespoke steal — resolved in engine (SPECIAL_ACTS).
  },
  {
    id: 'soldat_chevalier_cuivre',
    name: 'Chevalier de Cuivre Tout Nu',
    faction: 'soldat',
    type: 'INVOCATION',
    rank: 'A',
    image: 'soldat_chevalier_cuivre.jpg',
    baseHp: 90,
    baseAttack: 90,
    attackName: 'Burning Copper Attack',
    attackDesc: "Culture de l'Aura — +10 attaque à chaque début de tour. Sacrifie tous les équipements de cuivre.",
    summoningConditions: [{ type: 'SACRIFICE_OBJECT', match: { tag: 'cuivre' }, count: 2 }],
    effects: [{ trigger: 'PASSIVE', action: 'GAIN_ATTACK_PER_TURN', value: 10, text: "Culture de l'Aura" }],
  },
];

/** Map for O(1) lookups. */
export const CARD_MAP: Record<string, CardDef> = Object.fromEntries(CARDS.map((c) => [c.id, c]));

export function getCard(id: string): CardDef {
  const c = CARD_MAP[id];
  if (!c) throw new Error(`Unknown card id: ${id}`);
  return c;
}

export function allCards(): CardDef[] {
  return CARDS;
}

export function cardsByFaction(faction: Faction): CardDef[] {
  return CARDS.filter((c) => c.faction === faction);
}

export function heroForFaction(faction: Faction): CardDef {
  const hero = CARDS.find((c) => c.faction === faction && c.type === 'HERO');
  if (!hero) throw new Error(`No hero for faction ${faction}`);
  return hero;
}
